<a href="https://colab.research.google.com/github/Ojasav-Rathore/DeepLearningLab/blob/main/DL_LAB1_25AFI13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
t1 = torch.tensor([1,3,4,5,3,6])
print(t1.size())
print(t1.type())

torch.Size([6])
torch.LongTensor


In [3]:
t2 = torch.tensor([[2,4,5],
                  [1,5,8]])
print(t2.size())
print(t2.type())

torch.Size([2, 3])
torch.LongTensor


In [4]:
t3 = torch.tensor([[[12,34,5,3],[2,4,5,56]],
                   [[12,34,5,3],[2,4,3,56]],
                   [[12,34,5,3],[2,5,3,56]]])
print(t3.size())
print(t3.type())

torch.Size([3, 2, 4])
torch.LongTensor


In [5]:
a = torch.tensor([[2,4,5],
                  [1,5,8]])
b = torch.tensor([[2,4,5],
                  [1,5,8]])

add = a + b
print("Element wise addition",add)

subtract = a - b
print("Elementwise subtraction ", subtract)

multiply = a * b
print("Element wise product",multiply)

division = a / b
print("Element wise division ", division)

Element wise addition tensor([[ 4,  8, 10],
        [ 2, 10, 16]])
Elementwise subtraction  tensor([[0, 0, 0],
        [0, 0, 0]])
Element wise product tensor([[ 4, 16, 25],
        [ 1, 25, 64]])
Element wise division  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [7]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

t1, t2 = torch.tensor([0, 1]), torch.tensor([2, 3])
torch.dot(t1, t2)

tensor(3)

In [8]:
inputs = torch.tensor([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

weights = torch.tensor([
    [0.5, -0.1, 0.2],
    [0.8, 0.1, -0.3],
    [0.2, -0.5, 0.4],
    [0.1, 0.9, -0.1]
])

z_matmul = torch.matmul(inputs, weights)

print(z_matmul)
print(z_matmul.shape)

tensor([[3.1000, 2.2000, 0.4000],
        [9.5000, 3.8000, 1.2000]])
torch.Size([2, 3])


In [9]:
a = torch.tensor([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100 ,110, 120]
])
print(a[0:2])
print(a[:,1:3])
a[:,:]

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])
tensor([[ 20,  30],
        [ 60,  70],
        [100, 110]])


tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])

In [10]:
print(a[1])
print(a[1].shape)
print(a[1:2])
print(a[1:2].shape)

tensor([50, 60, 70, 80])
torch.Size([4])
tensor([[50, 60, 70, 80]])
torch.Size([1, 4])


In [11]:
#batches 2, channels  3 , features 4
T = torch.arange(2*3*4)
print(T.shape)

T = T.reshape(2,3,4)
print(T)

print(T.shape)
T[0]

torch.Size([24])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
T[:, 1, :]

tensor([[ 4,  5,  6,  7],
        [16, 17, 18, 19]])

In [13]:
T[:, 1:, :2]

tensor([[[ 4,  5],
         [ 8,  9]],

        [[16, 17],
         [20, 21]]])

In [14]:
img  = torch.randn(1, 3, 5, 5)
print(img)
crop = img[: , :, 1:3, 1:3]
print(crop)

tensor([[[[-8.6686e-01,  1.0304e+00, -6.9054e-01,  1.3486e+00, -3.6570e-01],
          [ 1.8813e+00,  4.0338e-01,  2.4522e-01,  1.2694e+00, -1.1509e+00],
          [-1.8886e-02,  3.2712e-01,  8.7745e-01, -2.9261e-01, -1.1239e-01],
          [-1.0447e+00,  5.5599e-01,  1.2965e+00, -8.7472e-02, -5.9096e-01],
          [-1.9551e-01,  1.7404e+00, -1.0171e+00,  1.6567e-01,  5.2494e-01]],

         [[ 5.0265e-01, -2.3194e-01,  1.2168e-01, -3.3577e-01, -6.2507e-01],
          [ 1.9001e+00,  6.4739e-01, -4.6499e-01,  1.9675e+00,  1.5903e+00],
          [-1.1583e-01,  2.4897e-01,  1.3528e+00, -5.5160e-01,  1.3264e+00],
          [ 1.0358e+00,  2.3417e-01, -4.1794e-01, -1.2084e+00, -1.7450e+00],
          [-4.6599e-01,  5.7913e-01, -7.7525e-01,  6.0741e-01, -7.2695e-01]],

         [[ 8.5071e-01,  9.4001e-01,  5.5798e-01,  3.0184e-02,  1.8162e-01],
          [-7.7196e-01, -3.1240e-02, -2.4018e+00, -4.6083e-01, -1.7631e-01],
          [-7.9563e-01,  1.0013e+00,  3.1993e-01,  2.0836e+00, -1.2789e+

In [15]:
a = torch.tensor([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100 ,110, 120]
])

In [16]:
mask = a>50
print(a[mask])
print(a[a>50])

tensor([ 60,  70,  80,  90, 100, 110, 120])
tensor([ 60,  70,  80,  90, 100, 110, 120])


In [17]:
a[a[:,1] > 50]

tensor([[ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])

In [18]:
a[:, 0] = 0
print(a)

tensor([[  0,  20,  30,  40],
        [  0,  60,  70,  80],
        [  0, 100, 110, 120]])


In [28]:
b = torch.arange(1 , 17)
print(b)

c = b.view(4,4)
print(c)
print(c.shape)

d = b.view(2,2,4)
print(d)
print(d.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
torch.Size([4, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]])
torch.Size([2, 2, 4])


In [30]:
e = torch.reshape(b, (4, 4))
print(e)
print(e.shape)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
torch.Size([4, 4])


In [35]:
unsquezeed_tensor = torch.unsqueeze(e, 1)
print(unsquezeed_tensor)
print(unsquezeed_tensor.shape)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]],

        [[13, 14, 15, 16]]])
torch.Size([4, 1, 4])


In [37]:
squeezed_tensor = torch.squeeze(unsquezeed_tensor)
print(squeezed_tensor.shape)

torch.Size([4, 4])


In [39]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([10, 20, 30])

print(A+B)
print(A*B)

tensor([[11, 22, 33],
        [14, 25, 36]])
tensor([[ 10,  40,  90],
        [ 40, 100, 180]])


In [40]:
C = torch.tensor([[1],
                  [2]])

print(A+C)
print(A*C)

tensor([[2, 3, 4],
        [6, 7, 8]])
tensor([[ 1,  2,  3],
        [ 8, 10, 12]])
